command: ["streamlit", "run", "app.py"]

env:
  - name: TARGET_WORKSPACE_HOST
    value: "https://adb-830380622316336.16.azuredatabricks.net"

  - name: TARGET_JOB_ID
    value: "83231014069212"

  - name: TARGET_VOLUME_DIR
    value: "/Volumes/databricks_dev_mxc_dbw_001/labapps/excel_uploads"
  
  - name: TARGET_TASK_KEY
    value: "Procesamiento_de_exceles"